version: "3.7"
services:
    aem-app:
        image: aem-app:latest
        container_name: aem_app_dev
        build:
            .
        ports:
        -   8080:8080
        volumes:
            - ${PWD}/log:/log